services:
  tomcat:
    build:
      context: .
      target: tomcat-run
    container_name: tomcat-app
    ports:
      - "8080:8080"
    volumes:
      - maven-cache:/root/.m2 

    networks:
      - backend
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${postgres_user}
      POSTGRES_PASSWORD: ${postgres_password}
      POSTGRES_DB: ${postgres_db}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "9080:80"
    depends_on:
      - db
    networks:
      - backend


  jasperserver:
    image: retriever/jasperserver:7.5.0
    container_name: jasperserver
    ports:
      - "9081:8080"
    environment:
      - DB_TYPE=postgresql
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=admin
    volumes:
      - ./jasperserver-import:/jasperserver-import
    depends_on:
      - db
    networks:
      - backend

volumes:
  pgdata:
  maven-cache:

networks:
  backend:
    driver: bridge
