services:
  tomcat:
    build:
      context: .
      target: tomcat-run
    container_name: tomcat-app
    ports:
      - "8080:8080"
    volumes:
      - maven-cache:/root/.m2 

    networks:
      - backend
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${postgres_user}
      POSTGRES_PASSWORD: ${postgres_password}
      POSTGRES_DB: ${postgres_db}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - backend

volumes:
  pgdata:
  maven-cache:

networks:
  backend:
    driver: bridge
